# Generated by Django 5.2.12 on 2026-04-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_country_remove_vacancy_category_job'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
