# Generated by Django 5.2.12 on 2026-04-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_country_remove_vacancy_category_job'),
        ('users', '0002_skill_rename_location_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
