# Generated by Django 5.2.11 on 2026-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_required_skills_delete_jobcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='hh.uz', max_length=50),
        ),
    ]
